name: Deploy Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean compile package -DskipTests

      - name: Set image names
        run: |
          REPOSITORY=$(echo "${GITHUB_REPOSITORY,,}")
          IMAGE_NAME="${REPOSITORY#*/}"
          DOCKERHUB_IMAGE_NAME="ghcr.io/${REPOSITORY}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          echo "DOCKERHUB_IMAGE_NAME=$DOCKERHUB_IMAGE_NAME" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build \
            --build-arg BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
            -t "$DOCKERHUB_IMAGE_NAME:latest" -t "$DOCKERHUB_IMAGE_NAME:${GITHUB_SHA::8}" .

      - name: Docker login
        run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Push image to ghcr.io
        run: |
          docker push "$DOCKERHUB_IMAGE_NAME:latest"
          docker push "$DOCKERHUB_IMAGE_NAME:${GITHUB_SHA::8}"

      - name: Deploy with SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DOCKER_HOST }}
          username: ${{ secrets.DOCKER_USER }}
          privateKey: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          command: |
            cd ~/signalsbot
            docker compose pull
            docker compose down
            docker compose up -d
